### ISSUE TITLE
RSS Issue

### ISSUE THREAD

**Issue by tuannvm** [rashidkpc/kibana2#102]
When i press rss button, it showed me these error:

NoMethodError at /rss/eyJzZWFyY2giOiIiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6ImFsbCIsImdyYXBobW9kZSI6ImNvdW50Iiwic3RhbXAiOjEzNTAzNjAxMjQ1NzQsInRpbWUiOnsidXNlcl9pbnRlcnZhbCI6MH19
undefined method `[]' for nil:NilClass

```
file: kelastic.rb
location: flatten_response
line: 320
```

BACKTRACE

(expand)

JUMP TO: GET POST COOKIES ENV

```
/home/Kibana/lib/kelastic.rb in flatten_response
    response['hits']['hits'].each do |hit|
kibana.rb in block in <main>
    flat = KelasticResponse.flatten_response(result.response,req.fields)
```

Ruby 1.9.3 with elasticsearch 0.19.10
How can we fix it?

Thanks!

**Comment by rashidkpc** [comment]
I'm not able to replicate this, do you get this every time you use the rss feed or only in some situations? Are you seeing the same behavior on http://demo.kibana.org:5601 ?

**Comment by tuannvm** [comment]
Yes, I get this everytime. I checked your demo site, and rss feature is good, but not my deployment.
I attached the image with my reply, please check it out.
I have tried ruby 1.8 also, but it didn't work either.
http://i47.tinypic.com/1rel41.png

Thanks!

**Comment by tuannvm** [comment]
Update: Kibana and Elasticsearch are on the same server so this error happen. If they are separated, it's ok.
Thanks Rashikpc!

**Comment by rashidkpc** [comment]
Pretty sure I fixed this, not sure why I couldn't replicate it, but it was likely related to the export issue you filed and occured when no fields were selected. Thanks for the tip!

**Comment by tuannvm** [comment]
Now it happened again with your latest build.

**Comment by fredleger** [comment]
still hapenning for me
