### ISSUE TITLE
Replace curb and curl with something Ruby

### ISSUE THREAD

**Issue by moll** [rashidkpc/kibana2#107]
Hey,

I'm giving Kibana a try and the curb gem it uses has a lot of dependencies (a few dozen megs of -dev libraries just to compile curb). It seems Curb is only used once for a POST in `lib/kelastic.rb`. How about switching to Ruby's HTTP and its POST there?

**Comment by bfritz** [comment]
+1 from me if curl is not necessary. As of a few days ago, curb was a pain to build on Debian Wheezy.  My work around and other details at bfritz/Kibana@077fbb1c76.

**Comment by moll** [comment]
I'm already working on replacing Curb with Ruby's net/http, so I'll get back to you.

**Comment by moll** [comment]
And done: https://github.com/rashidkpc/Kibana/pull/108
You may use my [fork of Kibana](https://github.com/moll/kibana) ([ZIP download](https://github.com/moll/kibana/zipball/kibana-ruby)) until this gets merged to master if you're in a hurry.

**Comment by rashidkpc** [comment]
Thanks for the pull moll, just merged
