### ISSUE TITLE
can not access kibana using IP address

### ISSUE THREAD

**Issue by flyasfish** [rashidkpc/kibana2#122]
Installed kibana ruby version, and found out when using IP address, kibana is not accessible.

[root@sulog01 ~]# wget http://10.100.2.168:5601
--2012-10-29 17:48:59--  http://10.100.2.168:5601/
Connecting to 10.100.2.168:5601... failed: Connection refused.

When use localhost, it's working fine.

[root@sulog01 ~]# wget http://localhost:5601
--2012-10-29 17:49:17--  http://localhost:5601/
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:5601... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4440 (4.3K) [text/html]
Saving to: `index.html.3'

100%[================================================================================>] 4,440       --.-K/s   in 0s

2012-10-29 17:49:17 (470 MB/s) - `index.html.3' saved [4440/4440]

The error is connection refused, it looks like kibana disabled access from external, we need to access kibana from other machines. Please suggest where to change the permission configs.

**Comment by rashidkpc** [comment]
Kibana listens only on localhost by default

See KibanaConfig.rb line 16. Change 127.0.0.1 to 0.0.0.0 to bind to all addresses

  # The adress ip Kibana should listen on
  KibanaHost = '127.0.0.1'

**Comment by flyasfish** [comment]
Thanks it worked fine now after apply the change.
