### ISSUE TITLE
Feature : authentication and log display authorization

### ISSUE THREAD

**Issue by prune998** [rashidkpc/kibana2#143]
I posted some changes to the code back when Kibana was a PHP application. It was straitforward : 
- do the auth with Apache htaccess
- define a list of user:filter in the config file
- compare the authed user name and force apply the filter

I have no  idea how to code that in Ruby though...

The need is to be able to use any standard auth mecanisme and pre-build a AND filter so users can only search for logs they are authorized to...

**Comment by untergeek** [comment]
I would love something like this: per user filtering, or per group filters.  I had to make an install per filter and this would be really helpful.

**Comment by rashidkpc** [comment]
Progress on this can be tracked in the kibana-ruby-auth branch that @jimi1283 and @awheeler have been working on. It is designed to be modular. An http auth module would be pretty trivial once we're ready to merge it in

**Comment by prune998** [comment]
HTTP auth module was a way to have auth for Kibana (php) the easy way... 
If Kibana have an internal login/group/log filter feature, it is even better.

I saw they made a auth_ldap module, which is what I need/want/use with mod_auth_ldap for now.

Waiting for the merge !!
