### ISSUE TITLE
Potential timezone bug?

### ISSUE THREAD

**Issue by eranrund** [rashidkpc/kibana2#156]
Hello,

I put data into ElasticSearch on a server set to the UTC timezone. Inside KibanaConfig.rb I also specified Timezone='UTC'. When I view my data, I notice the following things:
1) The graph time is in UTC, as expected
2) The @timestamp field is in UTC, as expected
3) The time range text boxes are in my local time
4) The 'Time' column is in my local time

Am I missing something or is this a bug?
I uploaded a screenshot to http://imgur.com/eoYA1 for your convenience.

Thanks :)

**Comment by rashidkpc** [comment]
Definitely a bug, introduced with the new timepicker. Should be fixed, thanks!

**Comment by eranrund** [comment]
Thanks for the quick response!
