### ISSUE TITLE
Feature request: Charting numeric statistical facet

### ISSUE THREAD

**Issue by azulcactus** [rashidkpc/kibana2#16]
I'm capturing application logs in my logstash which contain execution time.  The statistical facet provides min, max, average and more values when using a numeric field in elasticsearch.  It would be nice to add a new option in addition to trend and score for numerical fields which would somehow chart this data.

In this case it may not be a time chart but just a simple table with the statistical values, or it could take an increment period so you could ask for a statistical graph of averages broken down in 10 minute increments.

Here is the example elasticsearch query if I have a custom field defined of "time" (note: this field must be defined as a numeric type in the elasticsearch index).

POST http://server:9200/_all/_search{"query" : { "text" : {"@message" : "the_search_filter"} },"facets" : {"time_facet" : { "statistical" : {"field" : "time"} }}}

Results:
{  "took" : 2511,  "facets" : {    "time_facet" : {      "_type" : "statistical",      "count" : 2419946,      "total" : 1531886.968960829,      "min" : 0.0,      "max" : 19348.49609375,      "mean" : 0.6330252695559443,      "sum_of_squares" : 8.470505106146345E8,      "variance" : 349.62796172029414,      "std_deviation" : 18.698341148890567    }  }}

**Comment by rashidkpc** [comment]
I like this idea, I'm just not totally sure the best way to implement it. Trying to detect the field type from the ES mapping seems overly complex, plus the same field could possibly be defined as two different types. I'm thinking the best way would be to offer the option regardless of field type and simply tell the user it failed if facet fails.

**Comment by azulcactus** [comment]
Sure, type detection would be optional.  If you do a statistical facet with a non-numeric field you simply get an exception from ES, no big deal.  The screen may look something like:

<Bar chart, statistical number on the Y axis, time on the X axis>

<time range selector like is present today on Kibana's charting page, defaults to whatever was the time range on the prior search>

<interval selector, Kibana can pre-calculate an interval like it does today based on the time range to make the chart look pretty (not too few, not too many bars), user can optional adjust the interval so they can get the aggregations for every slice of 1 minute, 5 minutes, 30 minutes, or whatever>

<statistical value selector: user can select min, max, average, sum of squares, variance, standard deviation.  Kibana could default to average.  Whatever is selected will be charted and the value for the Y axis.  Supporting charting of multiple series simultaneously would be cool>

raw data appears at the bottom in a table view (user selected a 10 minute interval):

Range                     Min            Max            Average          Total Count
08:00:00-08:09:59    0.002         1.235           0.641             13221
08:10:00-08:19:59    0.054         2.721           0.357             34427

**Comment by rashidkpc** [comment]
May have to back this out. The stastical facet is proving to have the same issues as the terms facet, it can run elasticsearch out of memory and crash the cluster. Darn.

**Comment by azulcactus** [comment]
This is awesome!  I've got a 2 node cluster, 4 GB heap per JVM, and about 50 million documents over 50 GB of storage.  It works seamlessly, but will keep testing.

**Comment by rashidkpc** [comment]
Glad its working for you. Be careful attempting to run it against non-numeric fields until I get some kind of logic in there.

**Comment by rashidkpc** [comment]
This is long closed, but there is some logic in the ruby version to determine the field type without having to run the facet first.
