### ISSUE TITLE
Kibana in ruby doesn't show any results. 

### ISSUE THREAD

**Issue by timukas** [rashidkpc/kibana2#162]
Hi,

I've installed Kibana in ruby (different versions), configured according to readme. But not results are shown through web GUI.
Strange thing, that PHP Kibana (v0.1.5) is showing results correctly. And using MOBZ (web front end for an ElasticSearch) is also showing that there are some information.

Any ideas how to fix my issue?

regards,

**Comment by rashidkpc** [comment]
What does your KibanaConfig.rb look like?

**Comment by timukas** [comment]
Hello,

Only this lines were changed:
...
  Elasticsearch = "172.28.28.27:19200"
  KibanaHost = '172.28.28.27'
...
The rest of file uses default settings.

Here's line from config.php (older php-Kibana which works)
...
  'elasticsearch_server' => "172.28.28.27:19200",
...
The rest of settings are also default.

Here's some info about my setup:
OS is CentOS 6.3
Elasticsearch version: 0.19.8
Ruby version: ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]

Here's elasticsearch.yml settings:
...
cluster.name: logz
node.master: true
node.data: true
index.number_of_replicas: 0
path.data: /elastic/20121010/elasticsearch
path.work: /elastic/20121010/elasticsearch
path.logs: /elastic/20121010/elasticsearch
network.host: 172.28.28.27
transport.tcp.port: 19300
http.port: 19200
...

Hope this helps,

**Comment by rashidkpc** [comment]
Grab me (rashidkpc) on #logstash on freenode and we can debug it.

**Comment by rashidkpc** [comment]
Closing as can not replicate. Find me on irc we'rll debug
