### ISSUE TITLE
High precision time in Kibana UI

### ISSUE THREAD

**Issue by dav3860** [rashidkpc/kibana2#163]
We have implemented high precision timestamps in logstash (with milliseconds). However, in Kibana, the Time column only displays the seconds. 
Even after changing the time format in KibanaConfig.rb to include milliseconds (Time_format = 'yyyy/mm/dd HH:MM:ss.l'), Kibana shows Time like "2012/11/16 16:33:40.000". The milliseconds are always set to zero.

This is important when your setup handles a large number of events/sec, so as to display the events in the correct order.

**Comment by dav3860** [comment]
I must add that the @timestamp field in the elasticsearch index includes the milliseconds.

**Comment by VoodooZ** [comment]
+1 Still applies to absolute latest git which really messes up the proper ordering of events for our application logs.

**Comment by dav3860** [comment]
Thx !
