### ISSUE TITLE
Feature request: Make the date picker behavior smarter

### ISSUE THREAD

**Issue by azulcactus** [rashidkpc/kibana2#17]
A few behaviorial improvements around custom dates I'd like to request.

First, if you select a "Custom" time period, the date picker should appear if it isn't already on the screen.  For example, you do a default search for the last 15 minutes for something, find no results so no date picker shows up.  If you select Custom, it would be nice if it would then appear.

Second, if you change the date in the date picker by hand without using the popup helper, the Filter button does not appear.  You have to press enter or use the popup helper.  This results in my users hitting my third request below a lot...

Third, if you change the values in the date picker they are only acknowledged if you press the Filter button that appears.  If you press the Search button, even if you have Custom selected as the time period, your time adjustments since your last search are not honored.

**Comment by azulcactus** [comment]
Fixing this now

**Comment by azulcactus** [comment]
Done, submitted a pull request.

**Comment by rashidkpc** [comment]
thanks for the pull, looks good!
