### ISSUE TITLE
can't find index

### ISSUE THREAD

**Issue by geezerrrr** [rashidkpc/kibana2#171]
The following configuration can't find index correctly
Smart_index_pattern = 'logstash-%Y.%m.%d'

but indices exist in elasticsearch below:
logstash-2012.11.18
logstash-2012.11.19

I can only find it through whole name of index, for example:
Smart_index_pattern = 'logstash-2012.11.19'

I use ruby 1.9.3 and elasticsearch 0.19.11.

**Comment by rashidkpc** [comment]
Hmm, I can't seem to replicate this. Can you grab me on IRC in #logstash tomorrow and we can debug?
