### ISSUE TITLE
Unable to Search for Fields Containing Only a Dash

### ISSUE THREAD

**Issue by cdeck** [rashidkpc/kibana2#173]
My Apache logs often have a dash ("-") for fields that were not populated.  When I view my logs in Kibana the fields that are dashes show up as such, but Kibana does not allow me to search just for a field that contains a dash.

For example, the following search returns _all_ records, rather than just records where the user is a dash:
user:"-"

I did some searching and I'm not sure whether this is a limitation of Kibana or of elasticsearch.  FWIW, I did try escaping the dash to see if that helped and it did not.

**Comment by rashidkpc** [comment]
This comes down to the default elasticsearch terms analyzer for that field. You have a couple options

1) change that mapping of that field. Here's untergeek's blog post on his ES mapping. See the bits about 'not_analyzed' http://untergeek.com/2012/11/05/my-current-templatemapping/

2) Alternatively, you can do _missing_:user which will return events in which the field is not present or contains no terms. A single dash would count as no terms.
