### ISSUE TITLE
dash character in field considered as a separator in Terms facet

### ISSUE THREAD

**Issue by dav3860** [rashidkpc/kibana2#176]
We use the last release of Kibana. Some extracted fields include a dash character. If we create a terms facet of these fields, the dash is not escaped and considered as a separator. So, the facet shows weird values. Example : 
field : @source_host
sample values : "host-1", "host-2"
Terms facet : 
Rank    @source_host    Count   Percent Action
1   host 185    93.43%  
2   1   182 91.92%  
3   2   138 69.7%  
[...]

The "score" and "trend" views don't have this problem.

We see that with the dash character, but it may be useful to avoid problems with other special characters too.

**Comment by rashidkpc** [comment]
This is an elasticsearch configuration issue. You may consider setting @source_host to not_analyzed. Here's a good sample mapping:

http://untergeek.com/2012/11/05/my-current-templatemapping/

**Comment by dav3860** [comment]
Thank you Rashid. I modified the mapping in elasticsearch using a template. It solved the issue.

**Comment by xavierbaude** [comment]
Hello,

To avoid searching 2 hours in google, try this  

You can custom it with your own field.

curl -XPUT localhost:9200/_template/logstash_per_index -d '{
  "template": "logstash*",
  "settings": {
    "index.query.default_field": "@message",
    "index.cache.field.type": "soft",
    "index.store.compress.stored": true
  },
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "@message": {
          "type": "string",
          "index": "analyzed"
        },
        "@source": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@source_host": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@fields.syslog_hostname": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@fields.syslog_program": {
          "type": "string",
          "index": "not_analyzed"
        },  
        "@source_path": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@tags": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@timestamp": {
          "type": "date",
          "index": "not_analyzed"
        },
        "@type": {
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}'
