### ISSUE TITLE
Search Last 15m Not Working

### ISSUE THREAD

**Issue by organicveggie** [rashidkpc/kibana2#182]
This is a little strange, but searching over the past 15 minutes produces 0 results. Meanwhile, searching over the last 60m shows a whole bunch of results within the past 15 minutes.

The one thing that is a little different about our setup is the timezone. All of our logs and servers are running on CDT, but I'm looking at the data from a machine on PDT. And I have `Timezone = 'user'` in `KibanaConfig.rb`.

**Comment by rashidkpc** [comment]
The largest reason we encounter for this is incorrect timestamps leading to events going into the "wrong" index. Logstash creates indices on UTC time, and Kibana uses that standard to deduce which index to look in for events in a given timeframe. Are you using the date{} filter? Shipping everything with a timezone? Grab me on IRC tomorrow and we'll get it sorted out.

**Comment by organicveggie** [comment]
User error. Log entries did not have a timezone. As a result, they were interpreted as UTC and got put into the wrong index for the last 6 hours of every day.

**Comment by blysik** [comment]
I'm having this problem too, but a little different.  @type:syslog works fine.  @type:apache has the issue where 15m has no results, 4h has plenty.

I have Apache logging in json, and logstash shipping to redis to ES without any filtering.  Here's what my timestamps look like:

"@timestamp": "2013-02-11T19:40:12-0800"

Is there anything wrong with this format?

**Comment by blysik** [comment]
I think this problem is getting clearer.  My apache logs aren't the problem.  They obviously have a timezone.  However, my @type:syslog messages don't.  They are in localtime, PST, and don't include an offset or anything.  So the date filter defaults to UTC.  I have to add an offset to the syslog messages.
