### ISSUE TITLE
Support running under sub-uri

### ISSUE THREAD

**Issue by ruckc** [rashidkpc/kibana2#183]
It would be nice to support Kibana running under a Sub-uri i.e. /kibana

**Comment by stonith** [comment]
I'm doing this via apache reverse proxy.

**Comment by lingej** [comment]
+1

```
        ProxyPass         /kibana-ruby/ http://localhost:5601/
        ProxyPassReverse  /kibana-ruby/ http://localhost:5601/
```

**Comment by ruckc** [comment]
With passenger... and DocumentRoot /var/www/html

`ln -sf /opt/kibana/static /var/www/html/kibana`

## kibana.conf

```
RackBaseURI /kibana
<Location /kibana>
AuthType CAS
require valid-user
</Location>
<Directory "/var/www/html/kibana">
Options -MultiViews
</Directory>
```

**Comment by jamtur01** [comment]
I'd actually recommend adding https://github.com/emk/sinatra-url-for/ to Kibana - it means this works out of the box instead of hacking around it in deployment.
