### ISSUE TITLE
Show query and http call to elasticsearch

### ISSUE THREAD

**Issue by thomasfr** [rashidkpc/kibana2#187]
For debugging and better understanding it would be great to have the ability to see the query and the complete http request which was executed to elasticsearch

**Comment by flyasfish** [comment]
+1
very good feature will be extremely useful for debugging.

**Comment by Nagilum23** [comment]
+1
and also very good for learning!

**Comment by rashidkpc** [comment]
Absolutely a great idea. Definitely planning to implement this.

**Comment by alouche** [comment]
Why not simply use something like Firebug (https://getfirebug.com/) and save the hassle to implement it in the app? See screenshot
![Kibana-Firebug](https://f.cloud.github.com/assets/110757/23276/5231b8f6-4a30-11e2-9375-f672edd376c2.png)

More than enough IMHO.

**Comment by dwlf** [comment]
@alouche my Firebug output doesn't look like that. Does recent Kibana still use the same mechanism?

+1

**Comment by rashidkpc** [comment]
You're really better off using Kibana 3 if you want this functionality. Click the little (i) icon on any panel to see the query that was used to generate it.
![screen shot 2013-10-15 at 2 11 45 pm](https://f.cloud.github.com/assets/1250387/1337966/7a816bf4-35de-11e3-9e53-93e9d63add8d.png)

**Comment by dwlf** [comment]
@rashidkpc very nice, very subtle!

Should this issue be closed then?

**Comment by rashidkpc** [comment]
Sure why not. Implemented in Kibana 3
