### ISSUE TITLE
Problems running kibana with Passenger

### ISSUE THREAD

**Issue by mrichar1** [rashidkpc/kibana2#192]
I have a working kibana installation using ruby directly (localhost:5601)

Using passenger 3.0.17 on rhel6.3 (from epel:http://dl.fedoraproject.org/pub/epel/6/x86_64/) with the following rubygem versions:

fastthread-1.0.7
rake-0.8.7
daemon-controller-1.0.10
rack-1.4.1

I've done the following:

ln -s /opt/kibana/static /opt/kibana/public

/etc/httpd/conf.d/kibana.conf : 

<VirtualHost *:80>
  ServerName log.example.com
  DocumentRoot /opt/kibana/public
  <Directory /opt/kibana/public>
     AllowOverride all
     Options -MultiViews 
  </Directory>
</VirtualHost>

Having restarted apache, I then access log.see.ed.ac.uk in the browser, and while I get the kibana header and images, I see a 404 error for api/search#

In error_log I see:

Apache/2.2.15 (Unix) DAV/2 Phusion_Passenger/3.0.17 mod_ssl/2.2.15 OpenSSL/1.0.0-fips configured -- resuming normal operations
[Thu Dec 06 10:43:12 2012] [error] [client 192.168.183.3] File does not exist: /var/www/public/js, referer: http://log.example.com/
[Thu Dec 06 10:43:13 2012] [error] [client 192.168.183.3] File does not exist: /var/www/public/js, referer: http://log.example.com/
[Thu Dec 06 10:43:13 2012] [error] [client 192.168.183.3] File does not exist: /var/www/public/api, referer: http://log.example.com/

Chrome devtools show that the 404 is triggered from line 4 of jquery.min.js loading /api/search/eyJz... etc

I feel like this might be a missing dependency, or a bit of ruby code not functioning properly.  Any ideas?

**Comment by mrichar1** [comment]
Resolved this issue - had placed kibana in a directory outside of /var/www from where cgi-esque actions weren't allowed.  Moving to /var/www/kibana and adjustign conf fixed this problem.

**Comment by ghost** [comment]
Hi there

I am facing the same problem. Any chance you could post your working configuration ?

Thanks in advance
