### ISSUE TITLE
Can't get "Smart_index_pattern = 'logstash-%Y.%m.%d-%H'" to work

### ISSUE THREAD

**Issue by truthtrap** [rashidkpc/kibana2#195]
Hi all,

We are working hourly indices, created by logstash. But we can't get this to work with Kibana.

Smart_index_pattern = 'logstash-%Y.%m.%d-%H'

does not work for us. (Indices are there, for example logstash-2012.12.10-14.)

Thanks,
Jurg.

**Comment by truthtrap** [comment]
I found the commit with a fix for this!

Thanks,
Jurg.

**Comment by rashidkpc** [comment]
Just merged that pull

**Comment by jamtur01** [comment]
This breaks Kibana for me as the LogStash default indexes doesn't have hourly in them. Might be worth leaving as the default minus hours and then add a doc update explaining how to index hourly?

**Comment by jamtur01** [comment]
Or make it an array with both options?

**Comment by jamtur01** [comment]
See https://github.com/rashidkpc/Kibana/pull/198.
