### ISSUE TITLE
Cannot see anything in Kibana UI

### ISSUE THREAD

**Issue by utsahdevops** [rashidkpc/kibana2#197]
I have been following centralized logging article from logstash 
http://logstash.net/docs/1.1.5/tutorials/getting-started-centralized

Trying to run Kibana along with it, but I dont see anything on Kibana UI . 
I am able to run a curl on elasticsearch and see the data. 

Is there anything that I am missing ?

Let me know what more information can I provide ?

**Comment by rashidkpc** [comment]
There was a breaking pull to the config file merged on accident yesterday, pulling today should fix it. Thanks

**Comment by utsahdevops** [comment]
Thanks. Works very well now. 
Also wanted to thank you for this project.
