### ISSUE TITLE
Search timeout (score option)

### ISSUE THREAD

**Issue by nicovpp** [rashidkpc/kibana2#212]
Hello,

When I am trying to make a large research with Kibana with score or trend option, I am getting the following error (after around 60s)  on the web interface : 

---

Oops! Something went terribly wrong.
I'm not totally sure what happened, but maybe refreshing, or hitting Reset will help. If that doesn't work, you can try restarting your browser. If all else fails, it is possible your configuation has something funky going on.
## If it helps, I received a 0 error from: api/analyze/@fields.pool_member/score/eyJzZWFyY2giOiJAZmllbGRzLnBvb2xfbWVtYmVyOioiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6ImN1c3RvbSIsImdyYXBobW9kZSI6ImNvdW50IiwidGltZSI6eyJmcm9tIjoiMjAxMi0xMC0wMVQxMDo1MzoxNiswMTowMCIsInRvIjoiMjAxMi0xMi0yMFQxMDowODoxNiswMTowMCIsInVzZXJfaW50ZXJ2YWwiOiIwIn0sInN0YW1wIjoxMzU1OTk4NzE0OTI5LCJtb2RlIjoic2NvcmUiLCJhbmFseXplX2ZpZWxkIjoiQGZpZWxkcy5wb29sX21lbWJlciJ9?_=1355998736665

It seems to be related to a timeout (CPU usage is still 100% and request seems to continu to be executed).

Do you know if there is a way to change this timeout or something else ?

I works fine with small researches.

**Comment by nicovpp** [comment]
I am using rashidkpc-Kibana-41a1298

I have alreay try to change the ElasticSearch Timeout without success :
#Set the Net::HTTP read/open timeouts for the connection to the ES backend
  ElasticsearchTimeout = 50000

**Comment by nicovpp** [comment]
I have just try Kibana's last version : rashidkpc-Kibana-v0.2.0-17-gedb4553

I see that score / trend analysis are by default limited to the last 2000 events. If I increase this limitation  (to 50'000) I am still getting the same error in aroud 30s, and the request seems to be stopped in the same time

**Comment by ghost** [comment]
I am experiencing the same issue.  It doesn't appear to be using ES when it times out, but a processing timeout after the ES query is done.  I can successfully run this up to about 30k queries.

Oddly, the CPU usage does not go down after the query times out as noted above.

Is there a way to optimize these queries to be heavier on ES and lighter in the ruby-side processing, or at the very least, allow them to be multithreaded in some way?

**Comment by rashidkpc** [comment]
You can use the Terms option and map the fields you want to use it with to be not_analyzed. This has roughly the same affect as the Score function, but moves processing to Elasticsearch instead of ruby

**Comment by dav3860** [comment]
I had this issue too. As I understand it, it's the Thin web server that closes the connection from the client to the api after 30s if elasticsearch takes too long to respond. I didn't find a way to set a configurable timeout. So I moved to NGINX + Passenger and it solved the problem.

**Comment by nicovpp** [comment]
@rashidkpc -> Ok I wiil try soon to use the Terms option on ES not_analyzed fields and keep you informed about the result
@dav3860 -> So you resolve this issue by using Passenger/NGINX. I have tried to make a similar setup (PASSENGER/HTTPD) but I am experiencing another issue: some charts are not displayed, as the pie chart in Terms option (see: https://github.com/rashidkpc/Kibana/pull/62). Is it working for you ?

**Comment by nicovpp** [comment]
@rashidkpc -> I have just tried on a not analyzed field for 200'000 events.
The behaviour is still the same for me. First ES process is taking CPU and then decrease. After, only kibana process is taking CPU and then I received Kibana's error

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  4386 root        20   0 2174m 1.1g  528 S 99.7 56.6   0:37.02 ruby

Also when this request failed I then need to kill kibana process.

Terms option is working fine (answer in 2s) on these 200'000 events.

**Comment by untergeek** [comment]
What happens to elasticsearch if you run the search directly in the REST API (make a curl call)?

--Aaron

**Comment by dav3860** [comment]
@nicovpp : yes the pie chart is OK. Remember you must create a symbolic link "public" pointing to the "static" directory for Kibana to work with Passenger. And maybe clear your browser cache.
For your 200,000 events tests, "score" is implemented in ruby, not elasticsearch. This explains why the ruby process is taking CPU too. To me, it's just that if the computation takes too long (>30s), the included Thin web server closes your connection to the Kibana API. 
@untergeek : in my case, it worked.

**Comment by untergeek** [comment]
Worked wasn't exactly the question. The question was, "What happens to elasticsearch when you make the query?"  Descriptions of top, vmstat, etc. would be the idea here.

**Comment by dav3860** [comment]
Elasticsearch isn't the problem (for the 30s timeout). It's clearly an issue with the web server that closes the connection (in my setup).

**Comment by nicovpp** [comment]
@dav3860 : Symbolic link was ok. I have just made again same setup (or probably not) and all graphs are now working but only on old versions of Kibana (Oct / Nov 2012)

On the last version of Kibana (Dec 12 and current version), I get a 500 error when trying to access the defaut page

I received a 500 Internal Server Error from: api/search/eyJzZWFyY2giOiIiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6OTAwLCJncmFwaG1vZGUiOiJjb3VudCJ9?_=1357925382246

I do confirm that on old versions, httpd/passenger shows data for 200'000 events under score option

**Comment by dav3860** [comment]
Check your web server's error logs.

**Comment by nicovpp** [comment]
Problem solved !  I thought that passenger would write log in my virtualhost's log files but it was in apache's global error log (I didn't check this file last time).

I needed to add rake gem, and change settings for gemfile.lock file. Everything works fine now and I am able to request data on a large number of events

Thanks !

**Comment by lucabelluccini** [comment]
Is it not possible to make the timeout be taken into account by Thin?
I am in a really confined linux setup (no way to ask for installing something on our machines), so no nginx + passenger...

**Comment by jyotiruhil** [comment]
hi everyone

 nicovpp

i got the same error
could you please tell me in detail to resolve the error

500 internal server error
