### ISSUE TITLE
Terms Facet splitting log field 

### ISSUE THREAD

**Issue by nicovpp** [rashidkpc/kibana2#218]
Hello,

When I use the Terms option on a string field with values containing a '-' , terms split it as 2 different results.

By example : @mylog = httpd-service 
will return 2 entry : 
httpd      1
service  1 

This is not the case with trend / score options. 

I am using version rashidkpc-Kibana-edb4553

Is there a way to avoid this ?

Thanks

**Comment by dav3860** [comment]
See issue #176. The @mylog field needs to be set to not_analyzed in your elasticsearch mapping. Or use a custom analyzer.

**Comment by nicovpp** [comment]
Indeed I have just changed my mapping options and it works fine

Thanks for these informations ! I do close this issue
