### ISSUE TITLE
search phrases which include question marks, either literals or wildcards, do not behave in a predictable manner

### ISSUE THREAD

**Issue by jmindek** [rashidkpc/kibana2#230]
Here's an example of two problems of using the question mark as a wildcard:

In my test ES-Kibana installation, I search for 'Mediapartners'. There are many results.
1. I'd like to find occurrences of 'Mediapartners' or 'Mediapartner' so I change my query to 'Mediapartner?'. I receive the Oops! page. Of course I could submit a boolean query. But, the point is that I expect to be able to use the question mark wild card any where in the search phrase and as many times as necessary.
2. If I change the search phrase to 'Media?artner' or 'Media?ar?ners', I get results. If I search using two question marks in a row 'Mediapar??ers' I get an Oops. 

Here's an example of a problem escaping the the question mark to use it as a literal:
1. I want to find the token \"?page=company\". The phrase query "\"\?page=company\"" does this well. I would like to simplify this using the \* wildcard so I change my query to '*\?page=company\"'. This results in an Oops.

**Comment by rashidkpc** [comment]
Should be fixed in latest commit.
