### ISSUE TITLE
Cannot see anything in Kibana UI

### ISSUE THREAD

**Issue by utsahdevops** [rashidkpc/kibana2#232]
I have php-curl installed and Kibana was showing logs until before few hours after which it stopped. 
I do not see any errors anywhere. The Kibana page shows no results. 
logstash UI shows logs as expected, but Kibana does not. 
How do I troubleshoot it ?

**Comment by rashidkpc** [comment]
The PHP version of Kibana is deprecated. Please upgrade to kibana-ruby. Thanks!
