### ISSUE TITLE
Less results when searching for 48h as with searching for 24h. 

### ISSUE THREAD

**Issue by cnf** [rashidkpc/kibana2#233]
As you can see in the screenshots below, a search with a timeframe of 24 hours returns 4624 results, and the exact search over a 48 hour timeframe returns 63 results.

This doesn't seem right.

![kibana_err_1](https://f.cloud.github.com/assets/252949/49707/b1a64a8a-5977-11e2-9170-9c775a156745.png)
![kibana_err_2](https://f.cloud.github.com/assets/252949/49708/b1bbb280-5977-11e2-957e-907cf05d10bf.png)

The kibana in question was downloaded around the 2nd or 3rd of January (I do not know how to check for a version...)

**Comment by kiranos** [comment]
Here is my screenshots with the same issue:
![24h](http://i.imgur.com/XIM7rh.jpg)
![48h](http://i.imgur.com/7UPQQh.jpg)
![alltime](http://i.imgur.com/llbEL.jpg)

I also have errors with alltime, I get far less results. Using latest kibana from website at the time:
rashidkpc-Kibana-v0.2.0-19-ge8fe7f2.zip

**Comment by dav3860** [comment]
I don't have this issue. 
![image](https://f.cloud.github.com/assets/2794902/49898/b7763f28-5982-11e2-84fa-3e6c8ca43795.png)

![image](https://f.cloud.github.com/assets/2794902/49900/d03a7e20-5982-11e2-9a9f-bd3e384a4b6c.png)

![image](https://f.cloud.github.com/assets/2794902/49901/e3991a30-5982-11e2-92f0-a50597ba378b.png)

Maybe you should try with the latest version. Have you tried to compare with a curl query ?

**Comment by kiranos** [comment]
Installed latest git master today and seems to be fixed for me
