### ISSUE TITLE
Issue in Kibana Start-up

### ISSUE THREAD

**Issue by pardeepchahal** [rashidkpc/kibana2#236]
I have installed kibana on ubuntu. 
I have changed KibanaConfig.rb with two entries
1.Elasticsearch = "107.21.226.196:9200" , where 107.21.226.196 is my hostname where I installed kibana and elasticsearch.
2. KibanaHost = '107.21.226.196'

But when i start kibana using sudo ruby kibana.rb, I am getting below exception.

> > Thin web server (v1.5.0 codename Knife)
> > Maximum connections set to 1024
> > Listening on 107.21.226.196:5601, CTRL+C to stop
> > /var/lib/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
> >         from /var/lib/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in`start_server'
> >         from /var/lib/gems/1.8/gems/thin-1.5.0/lib/thin/backends/tcp_server.rb:16:in `connect'

```
    from /var/lib/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:55:in `start'
    from /var/lib/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `call'
    from /var/lib/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /var/lib/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /var/lib/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    from /var/lib/gems/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    from /var/lib/gems/1.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in `run'
    from /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in `run!'
    from /var/lib/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
    from kibana.rb:332
```

Please suggest:

**Comment by rashidkpc** [comment]
107.21.226.196 is an EC2 IP. Is 107.21.226.196 actually assigned to an interface? I'm guessing its probably nat'd to a private address. Run ifconfig to find the actual address of your instance and use that.

**Comment by pardeepchahal** [comment]
Thanks - After I made these changes , my server is up and running. But when
I try to open in browser its not giving anything

 sudo ruby kibana.rb
== Sinatra/1.3.3 has taken the stage on 5601 for development with backup
from Thin

> > Thin web server (v1.5.0 codename Knife)
> > Maximum connections set to 1024
> > Listening on 10.212.65.213:5601, CTRL+C to stop

107.21.226.196 is static IP assigned to above machine and we have opened
port 5601 for that machine.

Server seems up and running but nothing is displayed in browser.

Oops! Google Chrome could not connect to 10.212.65.213:5601 error is coming.

Please suggest.

On Thu, Jan 10, 2013 at 10:01 PM, Rashid Khan notifications@github.comwrote:

> 107.21.226.196 is an EC2 IP. Is 107.21.226.196 actually assigned to an
> interface? I'm guessing its probably nat'd to a private address. Run
> ifconfig to find the actual address of your instance and use that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rashidkpc/Kibana/issues/236#issuecomment-12105265.

## 

With Best Regards,
Pardeep Chahal | Lead Consultant - Release and Configuration Management
Phone:  +91-9711689137 | Email: pardeep.chahal@hcentive.com
Skype : pardeepchahal4 | B-34/2, Sector-59, Noida- 201301
http://www.hcentive.com
Technology Solutions to Simplify Healthcare

**Comment by rashidkpc** [comment]
As this is EC2, you can't connect directly to your private IP, you need to connect through you public elastic ip. I'm closing this as it is not a Kibana issue.
