### ISSUE TITLE
elasticsearch with basic jetty authentication

### ISSUE THREAD

**Issue by heinemannj** [rashidkpc/kibana2#240]
500 Internal Server Error from: api/search

Is there a possibility to define UID and password in Kibana config file?
I have to secure elasticsearch with jetty basic auth.

Thanks!

**Comment by sacampa** [comment]
Hello.... did you find a solution for this:

"Is there a possibility to define UID and password in Kibana config file?
I have to secure elasticsearch with jetty basic auth"

I have the same problem.

Regards...

**Comment by heinemannj** [comment]
I think there is no further support for Kibana2
So upgrade to kibana3 and secure it with your webserver authentication features as described in Kibana3 FAQs
