### ISSUE TITLE
kibana cannot search contents from 'flume-ng + elasticsearch'

### ISSUE THREAD

**Issue by yrjsg** [rashidkpc/kibana2#244]
I used to use logstash to transfer log into elasticsearch and kibana worked well. Now I am using flume-ng, but kibana-search result is nothing. I have tried 'All Time' and get nothing either.

I've checked the elasticsearch is indexing with paramedic.

After that, I found the content is different between logstash and flume-ng. As below:

Logstash:
"_index" : "logstash-2013.01.07",
      "_type" : "tms_jboss_syslog",
      "_id" : "a_M9X_0YSpmE7A_bEzIFiw",
      "_score" : 1.0, "_source" : {"@source":"file://localhost.localdomain/tmp/logstash_test.log","@tags":[],"@fields":{},"@timestamp":"2013-01-07T10:53:50.941Z","@source_host":"localhost.localdomain","@source_path":"/tmp/logstash_test.log","@message":"[2013-01-05 11:02:19,969] packBoxNumber eq 00004000000044043412 createdOffice eq VIP_BJ:;null","@type":"tms_jboss_syslog"}

Flume-NG:
"_index" : "franklovelhy-2013-01-17",
      "_type" : "log",
      "_id" : "pluwSRdLRg2IxLyVsEwe-Q",
      "_score" : 1.0, "_source" : {"body":"[2013-01-05 11:02:19,969] It is frank log test","timestamp":"1358358759931"}

Is this caused by the 'timestamp' attribute of the content?

**Comment by dav3860** [comment]
The mapping and naming conventions of the indices need to match logstash's.

**Comment by yrjsg** [comment]
Thanks! I'm rookie on elasticsearch. I've heard of mapping and naming before. There will be a long time for learning. Thank you, dav!

**Comment by rashidkpc** [comment]
Gonna go ahead and close this, Kibana requires the logstash schema.

**Comment by yrjsg** [comment]
I've solved this problem, Chinese people can go to http://baniu.me/2013/01/kibana-in-flume/. Not-Chinese can email me baniu.yao at gmail.com.
