### ISSUE TITLE
Score fails unless number of events is very low

### ISSUE THREAD

**Issue by chris-wood-mobcast** [rashidkpc/kibana2#253]
Hi There,

When I try to do a score of @source_host, it always fails unless the number of events searched is very low, e.g. with 6,084 events it fails, but with 1,463 it works. The 6,084 events are all over the same day.

Here's an example error message from the UI: "If it helps, I received a 0 error from: api/search/eyJzZWFyY2giOiIiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6IjE0NDAwIiwiZ3JhcGhtb2RlIjoiY291bnQiLCJ0aW1lIjp7InVzZXJfaW50ZXJ2YWwiOjB9LCJzdGFtcCI6MTM1ODQxNjk0OTAyNH0=?_=1358416949028"

I have set max number of open files to 640000.

Any ideas on why this might be, and what I could do to allow scoring over larger sets of events would be greatly appreciated.

Regards,
Chris.

**Comment by dav3860** [comment]
Have a look at #212. It may be a timeout issue.

**Comment by chris-wood-mobcast** [comment]
I installed passenger, which has fixed it.

Cheers,
Chris.

**Comment by rashidkpc** [comment]
Thanks Chris, I should probably note that Passenger is the recommended method for deploying to production

**Comment by chris-wood-mobcast** [comment]
It's certainly seems to perform a lot better now.

Thanks again,
Chris.

On 18 January 2013 14:39, Rashid Khan notifications@github.com wrote:

> Thanks Chris, I should probably note that Passenger is the recommended
> method for deploying to production
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rashidkpc/Kibana/issues/253#issuecomment-12424320.

## 

_Chris Wood_
_Systems Administrator
Mobcast Services Ltd - a TESCO Company_
07917 758 107
Skype: chriswood12385
64 Great Eastern Street, London EC2A 3QR
