### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by daveallen** [rashidkpc/kibana2#254]
I have other instances running.  I use a chef cookbook to install.  Just started getting errors since the last install a week ago.
I get this error when I try launch Kibana:

ruby kibana.rb 
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- tzinfo (LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /var/www/kibana/Kibana/lib/query.rb:3
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /var/www/kibana/Kibana/lib/kibana.rb:15
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from kibana.rb:4

**Comment by rashidkpc** [comment]
you probably need to re-run bundle install

**Comment by daveallen** [comment]
That is so weird.  I wiped out the install dir 3 times and ran bundle install all 3 times.  I even installed it in a completely separate directory by hand and ran bundle install and it did the same thing.  Now it won't fail any more.  lol  Thanks!  You must have scared it.
