### ISSUE TITLE
wrong search highlighting in fields different from @messages

### ISSUE THREAD

**Issue by heinemannj** [rashidkpc/kibana2#281]
If you search in fields different from @messages there is no highlighting in this fields - only in the not filtered field @messages:

Filterstring: @source_host:p*

![case-wrong-highlighting](https://f.cloud.github.com/assets/3251642/126628/d589b4a2-6f69-11e2-8360-ed15012a74d4.JPG)

**Comment by rashidkpc** [comment]
You can set the fields to highlight on in KibanaConfig.rb.

**Comment by heinemannj** [comment]
I have testet several things:

Highlighted_field = "@source_host" - works
Highlighted_field = "@message" - works
Highlighted_field = "@message, @source_host" - NOT working
Highlighted_field = "_all" - NOT working

  # A field needs to be specified for the highlight feature. By default, 
  # Elasticsearch doesn't allow highlighting on _all because the field has to 
  # be either stored or part of the _source field.
  Highlighted_field = "_all"

Myt ES mapping:

{
    "template_elma" : {
        "template" : "rsyslog-*",
            "settings" : {
                "index.number_of_shards" : 1,
                "index.cache.field.type" : "soft",
                "index.refresh_interval" : "30s",
                "index.store.compress.stored" : true,
                "index.query.default_field" : "@message",
                "index.number_of_replicas" : 0
            },
            mappings: {
                "events" : {
                    "_all": { "enabled": true },
                    "properties" : {
                        "@customer" : { "type" : "string", "index": "not_analyzed", "include_in_all" : true },
                        "@fields" : { "dynamic" : "true",
                            "properties" : {
                                "facility" : { "type" : "integer", "index": "not_analyzed" },
                                "facility_label" : { "type" : "string", "include_in_all" : true },
                                "priority" : { "type" : "integer", "index": "not_analyzed" },
                                "processid" : { "type" : "string", "index": "not_analyzed" },
                                "program" : { "type" : "string", "index": "not_analyzed" },
                                "severity" : { "type" : "integer", "index": "not_analyzed" },
                                "severity_label" : { "type" : "string", "index": "not_analyzed" }
                            }
                        },
                        "@message" : { "type" : "string", "include_in_all" : true },
                        "@source" : { "type" : "string", "index": "not_analyzed" },
                        "@source_host" : { "type" : "string", "include_in_all" : true },
                        "@timestamp" : { "type" : "date", "format" : "dateOptionalTime", "index": "not_analyzed" },
                        "@type" : { "type" : "string", "index": "not_analyzed" }
                    }
                }
            }
        }
    }
}
