### ISSUE TITLE
Display tags separately in analysis screen

### ISSUE THREAD

**Issue by organicveggie** [rashidkpc/kibana2#29]
It would be nice of the Analyze @tags screen displayed the tags such that we could click on individual tags, instead of only being able to search by sets of tags.

http://www.flickr.com/photos/organicveggie/6948471304/in/photostream/lightbox/

In our IRC conversation you wrote: it's in "collectFieldValues. The culprit is that implode(',', $value)".

**Comment by rashidkpc** [comment]
Note to self: This will affect any field stored as an array.

**Comment by kwilczynski** [comment]
+1 to this, very useful :)

**Comment by rashidkpc** [comment]
Fixed in kibana-ruby  9fee2db
