### ISSUE TITLE
Kibana dwelling in the past (5h ago, to be precise)

### ISSUE THREAD

**Issue by garthk** [rashidkpc/kibana2#298]
Kibana won't show events sent in the last five hours. The Logstash web interface does show them. All hosts are in the same time zone (EST). Changing `Smart_index` and `Timezone` settings doesn't help. Much discussed in IRC recently: I'm gathering info here to make group troubleshooting easier.

**Comment by garthk** [comment]
Ok, I think I've found the crux of the problem: ES and Kibana aren't handling time zones in the same way. 

Choosing “12h ago”, Kibana puts up a date range picker interface showing `2013-02-19 08:49:57` to `2013-02-19 20:49:57`, matching the `Tue Feb 19 20:49:57 EST 2013` timestamp on the hosts. 

The most recent item shown is from `02/19 15:49:54` (with `Timezone` set to `EST` to match the host). That's from five hours ago, but at least _some_ of Kibana is in the right time zone. 

The graph isn't showing anything. The progress bar keeps advancing and then beginning again. 

Kibana's first XHR request contains this ES query:

```
curl -XGET http://localhost:9200/_all/_search?pretty -d '{
  "query": {
    "filtered": {
      "query": {
        "match_all": {
        }
      },
      "filter": {
        "range": {
          "@timestamp": {
            "to": "2013-02-19T20:49:57-05:00",
            "from": "2013-02-19T08:49:57-05:00"
          }
        }
      }
    }
  },
  "from": 0,
  "sort": {
    "@timestamp": {
      "order": "desc"
    }
  },
  "size": 50,
  "highlight": {
    "fields": {
      "true": {
        "fragment_size": 9999
      }
    },
    "pre_tags": [
      "@KIBANA_HIGHLIGHT_START@"
    ],
    "post_tags": [
      "@KIBANA_HIGHLIGHT_END@"
    ]
  }
}'
```

The ES response begins:

```
"took" : 24,
"timed_out" : false,
"_shards" : {
  "total" : 65,
  "successful" : 65,
  "failed" : 0
},
"hits" : {
  "total" : 161145,
  "max_score" : null,
  "hits" : [ {
    "_index" : "logstash-2013.02.19",
    "_type" : "syslog",
    "_id" : "E_P0bhkIQoSdMob7d1crAg",
    "_score" : null, "_source" : {"@source":"file://HOSTNAME/var/log/auth.log","@tags":["sysloggy","grokked"],"@fields":{"timestamp":["Feb 19 15:49:54"],"logsource":["HOSTNAME"],"program":["sshd"],"pid":["11623"]},"@timestamp":"2013-02-19T20:49:54.255Z","@source_host":"HOSTNAME","@source_path":"/var/log/auth.log","@message":"Feb 19 15:49:54 HOSTNAME sshd[11623]: Connection closed by 10.23.23.23 [preauth]","@type":"syslog"},
    "sort" : [ "2013-02-19T20:49:54.255Z" ]
  }
```

I've checked the source host: it's logging with the correct time in EST. `Feb 19 15:49:54` gets parsed to a `@timestamp` field of `2013-02-19T20:49:54.255Z` by `grok` with a pattern of `%{SYSLOGBASE}`. 

Kibana's fiter is asking for records to `2013-02-19T20:49:57-05:00` (-05:00 denoting EST), but ES is responding with records ending `2013-02-19T20:49:54.255Z` (UTC). 

At which end is it easier to fix this? What should I check next?

**Comment by garthk** [comment]
`curl http://localhost:9200/_template/logstash_per_index` returns:

```
{
  "template": "logstash*",
  "settings": {
    "index.query.default_field": "@message",
    "index.cache.field.type": "soft",
    "index.store.compress.stored": true
  },
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "@message": {
          "type": "string",
          "index": "analyzed"
        },
        "@source": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@source_host": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@source_path": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@tags": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@timestamp": {
          "type": "string",
          "index": "not_analyzed"
        },
        "@type": {
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}
```

I don't believe I have any other views defined.

**Comment by rashidkpc** [comment]
I know we discussed this on IRC, but for posterity:

```
    "@timestamp": {
      "type": "string",
      "index": "not_analyzed"
    },
```

should be

```
    "@timestamp": {
      "type": "date",
      "index": "not_analyzed"
    },
```
