### ISSUE TITLE
Kibana not loading in browser

### ISSUE THREAD

**Issue by pdiaz1420** [rashidkpc/kibana2#305]
I pasted my server's ip with port 5601 in my my browser but it does not load.  All seems well on command line.  What do I need to check?

]# ruby kibana.rb
== Sinatra/1.3.3 has taken the stage on 5601 for development with backup from Thin

> > Thin web server (v1.5.0 codename Knife)
> > Maximum connections set to 1024
> > Listening on 127.0.0.1:5601, CTRL+C to stop

Firefox can't establish a connection to the server at localhost:5601.

**Comment by electrical** [comment]
Did you also try to connect to 127.0.0.1:5601 instead of localhost?
Otherwise you can also change it in the KibanaConfig file.

**Comment by pdiaz1420** [comment]
[root@logsrv132att Kibana-0.2.0]# ruby kibana.rb
== Sinatra/1.3.3 has taken the stage on 5601 for development with backup from Thin

> > Thin web server (v1.5.0 codename Knife)
> > Maximum connections set to 1024
> > Listening on 127.0.0.1:5601, CTRL+C to stop

In the browser I use the server ip

**Comment by electrical** [comment]
i guess the server ip is different then 127.0.0.1 ?
You might wanna change the binding in the KibanaConfig.rb file to let it listen to 0.0.0.0  ( all ip's )

if it still doesn;t work then, maybe a firewall is blocking it?

**Comment by rashidkpc** [comment]
electrical is likely correct, it sounds like you've installed on another server? Connecting to localhost would mean you've installed it on your workstation, if its on another system you need to put the IP address of that system (or 0.0.0.0) in KibanaConfig, then connect to it from your browser.

**Comment by pdiaz1420** [comment]
I was just about to reply back.  I changed the kibana host to my server and everything is good.  Thanks for all the help.
