### ISSUE TITLE
Add new option in order to define a default path for Kibana requests

### ISSUE THREAD

**Issue by duylong** [rashidkpc/kibana2#309]
For use the alias option with httpd .

**Comment by duylong** [comment]
https://github.com/duylong/Kibana/commit/e0b042bb1bbd3d73cabbee2a86dc394f3f0ea888

**Comment by duylong** [comment]
Sorry, my solution works with apache but not with ruby.

**Comment by rashidkpc** [comment]
This is doable with apache+passenger without a patch:
https://gist.github.com/semiosis/4658921
