### ISSUE TITLE
cannot search for fields that contain a dash (-)

### ISSUE THREAD

**Issue by furlongm** [rashidkpc/kibana2#311]
Fields that contain a dash (e.g. hostname-001, or a uuid) seems to search on substrings divided by the dash, rather than the full substring containing the dash.

Also a fields terms also get divided if there is a dash. So we have hostname such as e.g. xy-rcc112 and yz-rcc112 and cannot filter on these specific hostnames, only on xy or yz or rcc112.

**Comment by rashidkpc** [comment]
This is the expected default behavior. If you need to search for a value containing a hash you can enclose it in quotes eg field:"some-stuff". Analysis of indexed fields is down to your elasticsearch mapping, you may want to specify a different analyzer in your template

**Comment by furlongm** [comment]
I have tried with the following elasticsearch mapping but in kibana there is no difference in behaviour. Should there be, or are there further steps to make kibana not treat "-" as a token delimeter?

index:
  analysis:
    tokenizer:
      token_filter:
        word_delimiter:
          preserve_original: true
