### ISSUE TITLE
Kibana doesn't work on ES cluster node down szenario

### ISSUE THREAD

**Issue by praenti** [rashidkpc/kibana2#335]
Hi,

I have a typical installation of Kibana with logstash and elasticsearch. The elasticsearch is configured as a cluster "logstashcluster" with 2 nodes. Base setting are 5 shards with 1 replica. The rest is standard.
Kibana is configured for two nodes "single" and "single2" and works fine with this setup.

The problem now is when I'm shutting down one of the elasticsearch nodes, Kibana delivers a 500 Internal Server Error on api/search/...
Doing a curl search query on the shell working like a charm. As well logstash puts new events into the elasticsearch.
After starting the second node again, Kibana works again.

For me it looks like there is a bug in Kibana which prevents Kinbana to use a cluster as it is proposed.

Used versions:
Kibana 0.2.0
Ruby 1.8.7
Elasticsearch 0.20.6
Logstash 1.1.9
running on Ubuntu 12.04 LTS

**Comment by rashidkpc** [comment]
Kibana acts as a REST client. REST clients can not join the cluster. The best way to deal with this is to install elasticsearch on your kibana host, set node.data: false, and point kibana at localhost.
