### ISSUE TITLE
Kibana 0.2.0 doesn't return any results

### ISSUE THREAD

**Issue by vishalmanohar** [rashidkpc/kibana2#336]
To try out Kibana, I indexed some JSON docs as given in http://www.elasticsearch.org/guide/reference/api/index_/.

However, Kibana always returns this response while searching:
{"kibana":{"error":"no index","default_fields":["@message"],"time":{"from":"1970-01-01T05:30:00+05:30","to":"2013-04-15T09:23:28+05:30"}}}

ElasticSearch version 0.20.6

KibanaConfig   Elasticsearch = "localhost:9200"

**Comment by rashidkpc** [comment]
Kibana 2 requires the logstash schema and time format
