### ISSUE TITLE
Searching for '-' fails

### ISSUE THREAD

**Issue by lupujo** [rashidkpc/kibana2#345]
When searching a field for a match for '-', irrelevant results are returned in addition to the correct results. See attached screenshot after search took place. In the attached screenshot only 2 results are correct.
![g0](https://f.cloud.github.com/assets/4266230/437725/3c4c0c02-b0ac-11e2-929f-b2ec3b3aaeaf.png)

**Comment by rashidkpc** [comment]
This is not a Kibana issue. The standard ES mapping using - to seperate tokens. You can either change that field to not_analyzed, pick a different tokenizer, or search with _missing_:clientip

**Comment by lupujo** [comment]
Please reopen ticket.

1 - Your suggestion doesn't work.
Attached screenshots when searching for missing referrer - zero results (incorrect).
![g1](https://f.cloud.github.com/assets/4266230/437728/55970ef0-b0ac-11e2-870d-ea3b28e96aa7.png)

 and:

![g2](https://f.cloud.github.com/assets/4266230/437730/58e7e872-b0ac-11e2-8ccf-25c52d70c226.png)

2 - In Kibana UI, when clicking the "Magnifying glass" icon, the generated search query is in contrast to what you suggested above (at least this should count as a bug?):

![g4](https://f.cloud.github.com/assets/4266230/437732/5f44197a-b0ac-11e2-88a0-006b00c73ca5.png)

Clicking the icon produces the following search page (mixed results - incorrect):

![g3](https://f.cloud.github.com/assets/4266230/437731/5ca74b2e-b0ac-11e2-95b1-fb0e5db9197c.png)

**Comment by rashidkpc** [comment]
Markdown messed with the comment, should've read:  _missing_:clientip

**Comment by lupujo** [comment]
It's working - thank you.
So my bug report is that clicking the "Magnifying Glass" icon per screenshot above generates:
   @fields.referrer:"-"
Instead of:
   _missing_:referrer

**Comment by rashidkpc** [comment]
There's no way for Kibana to know what analyzer you are using for your fields. You might want to set a different analyzer for that field: http://www.elasticsearch.org/guide/reference/mapping/analyzer-field/

Alternatively, you might want logstash to just drop that field all together if it doesn't contain an IP.
