### ISSUE TITLE
Keep getting Network error during bundle install

### ISSUE THREAD

**Issue by errprone** [rashidkpc/kibana2#352]
newby here.. down loaded Kibana-0.2.0
installed ruby, gem install bundler with no problem

I keep getting the following error:
# bundle install

Fetching source index from http://rubygems.org/
Resolving dependencies........
Network error while fetching http://rubygems.org/quick/Marshal.4.8/json-1.7.5-java.gemspec.rz
# 

Not sure what the issue... I can do a "wget  http://rubygems.org/quick/Marshal.4.8/json-1.7.5-java.gemspec.rz' with no problem... is there a workaround?

thx

**Comment by rashidkpc** [comment]
Not a Kibana issue. Rubygems.org might be having an problem
