### ISSUE TITLE
Cannot parse logs by elements

### ISSUE THREAD

**Issue by kayrus** [rashidkpc/kibana2#356]
I use the following logstash config with standalone elasticsearch:

input {
  rabbitmq {
    type => "nginx_web"
    host => "elastic"
    exchange => "rawlogs"
    user => "logging"
    password => "pass"
  }
}

filter {
  grok {
    type => "nginx_web"
    pattern => "%{COMBINEDAPACHELOG}"
  }
}

output {
  elasticsearch {
  }
}

and tried search logs by fields, i.e. HOSTNAME, referrer, agent, etc. But these fields doesn't appear in Kibana web interface. I can see only:

@message
@source
@source_host
@source_path
@tags
@timestamp
@type

How can I enable per element log search?

**Comment by electrical** [comment]
Hi,

What is the 'type' you gave to the file entry at the shipper? ( agent )

**Comment by kayrus** [comment]
input {
  file {
    path => [ "/var/log/nginx/access_log" ]
    type => "all"
  }
}

output {
  rabbitmq {
    host => "elastic"
    exchange_type => "fanout"
    exchange => "rawlogs"
    user => "logging"
    password => "pass"
  }
}

**Comment by electrical** [comment]
The 'type' is set at agent level and is never changed afterwards.
You will need to set the 'type' of the grok filter to the same one as the file input. 'all' in this case.
Then it will work.

**Comment by kayrus** [comment]
I set type on the client side, "all" type on the server side and it works! Thanks a lot.

**Comment by electrical** [comment]
Your welcome :-)
