### ISSUE TITLE
Search indexes with special symbols

### ISSUE THREAD

**Issue by kayrus** [rashidkpc/kibana2#357]
Hello!

I've  tried to search apache logs by request string index and noticed that search doesn't work when request string contains special symbols.

For example the following search works well:

request:"/?q=query"

But this one fails (the log actually exists):

request:"/?q=%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%BA%D0%B8"

**Comment by rashidkpc** [comment]
This is down to elasticsearch mapping. You map want to change the analysis or tokenizing of that field

**Comment by kayrus** [comment]
Actually I guess that this is Kibana bug. When I tried to search with the following string (backslashed slash):

request:"\/?q=%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%BA%D0%B8"

search works well.

Is it possible to fix it?

**Comment by kayrus** [comment]
I mean the magnifier icon next to the field value.
