### ISSUE TITLE
derivedquery feature is breaking up a field on dashes

### ISSUE THREAD

**Issue by dwinter3** [rashidkpc/kibana2#373]
I am using @fields.stack for the field to split things up in the new derivedquery panel. However, it seems to be breaking a field up too deep when the field contains dashes. See the attached image.
![fields](https://f.cloud.github.com/assets/1416878/639278/ffc0d6b4-d2cf-11e2-8190-f956f57bcdd7.png)

**Comment by rashidkpc** [comment]
This is down to your elasticsearch mapping. Fields you use with derive queries should probably be set to not_analyzed. Also, please submit kibana 3 bugs on this repo: https://github.com/elasticsearch/kibana
