### ISSUE TITLE
Start Kibana on boot up

### ISSUE THREAD

**Issue by dparkar** [rashidkpc/kibana2#375]
I have a script which I would like to place under /etc/init.d so that Kibana would start on boot up.

In the script I have the following line : 

ruby /home/developer/Kibana/Kibana-0.2.0/kibana.rb &

If I try to run this script manually, or simple even if I try to run the above command directly Kibana fails to start with the following message :

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in 'require' : cannot load such file --  KibanaConfig (LoadError)
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
from /home/developer/Kibana/Kibana-0.2.0/kibana.rb:16:in '<main>'

But if I go to the folder /home/developer/Kibana/Kibana-0.2.0/ and run the following :

ruby kibana.rb &

Then that works fine.

When I googled, I think I saw people talking about this as an issue with the load path for ruby ?

But how do I solve this so that I can run Kibana on boot up, I can already run Logstash/Elasticsearch on bootup.

**Comment by stonith** [comment]
I'd suggest setting up Kibana with mod_passenger (Phusion Passenger) for Apache. It performs better and autostart apache is already included.

**Comment by rashidkpc** [comment]
You really want to use mod_passenger if you need this functionality
