### ISSUE TITLE
ruby kibana-daemon.rb start fails siliently

### ISSUE THREAD

**Issue by nodesocket** [rashidkpc/kibana2#376]
Running:

```
 ruby kibana-daemon.rb start
```

Simply exits immediately, without starting `kibana`. No errors or warnings printed.

Any ideas>

**Comment by aalwash** [comment]
Hi nodesocket,

I had the same issue, if you do 
ruby kibana-daemon.rb start -t

Then you will see the error that is making it crash.
I had a lot of missing packages and tmp directory wasn't created

Hopefully this will help other ppl as well

Good luck
