### ISSUE TITLE
Put popup for data timestamp below the graph

### ISSUE THREAD

**Issue by ghost** [rashidkpc/kibana2#380]
When graphing data, we shouldn't hide part of the graph with a dialog that shows one point on the graph. Instead, it's more readable to put the data below the graph.

As an example, the 4766 @ [timestamp] dialog here https://dl.dropboxusercontent.com/u/7815189/kibana/Screen%20Shot%202013-07-11%20at%2012.48.29%20PM.png should probably go below the graph, so it's not overlapping with the rest of it.

**Comment by rashidkpc** [comment]
wrong repo try this one: https://github.com/elasticsearch/kibana/issues
