### ISSUE TITLE
How to use greater than or less than query

### ISSUE THREAD

**Issue by rajeshtg78** [rashidkpc/kibana2#382]
The search query of greater than is not working in KIbana.. 

@fields.syslog_program:"offer-service" AND "/soap/availableOffers" AND @fields.dur: > 17

But this works @fields.syslog_program:"offer-service" AND "/soap/availableOffers" AND @fields.dur: 17

**Comment by rashidkpc** [comment]
Kibana uses Lucene query syntax. @fields.duh:[17 TO *]

https://lucene.apache.org/core/3_5_0/queryparsersyntax.html

**Comment by rajeshtg78** [comment]
if I use this syntax for number field , it is doing lexograohy search and not returning the expected result @fields.duh:[17 TO *]
