### ISSUE TITLE
How to use greater than or less than query

### ISSUE THREAD

**Issue by rajeshtg78** [rashidkpc/kibana2#384]
if I use this syntax for number field , it is doing lexograohy search and not returning the expected result @fields.duh:[17 TO *]

I created new issue as I am unable to open the #382.

**Comment by rashidkpc** [comment]
It is rather likely that your numbers are being stored as strings in elasticsearch. if you are using logstash and grok you might want to change your pattern to something like %{PATTERN:dur:int} to make sure that it is stored as an integer.

Closing as not a Kibana bug

**Comment by rajeshtg78** [comment]
Hi Rashid,

Could you pls explain how can I use %{PATTERN:dur:int} ?

---

Thanks and Regards,
Rajesh

**Comment by rashidkpc** [comment]
#logstash on freenode is a great resource for logstash questions. You can find me as rashidkpc in the #logstash channel.

**Comment by rajeshtg78** [comment]
I am not able to follow you. How can I go to logstash ?

---

Thanks and Regards,
Rajesh

**Comment by rajeshtg78** [comment]
We are using logstash tool only for our prod box ..

But duration query is not returning correct results, but for strings it does..

@fields.syslog_program:"offer-service" AND @fields.dur:["100" TO "10000"]

---

Thanks and Regards,
Rajesh

From: Rajesh Gangadharan
Sent: Tuesday, July 16, 2013 2:40 PM
To: 'rashidkpc/Kibana'
Subject: RE: [Kibana] How to use greater than or less than query (#384)

I am not able to follow you. How can I go to logstash ?

---

Thanks and Regards,
Rajesh
