### ISSUE TITLE
blank rows in kibana ui 

### ISSUE THREAD

**Issue by alienzrcoming** [rashidkpc/kibana2#397]
Hi,

I upgraded to logstash 1.2.0, elasticsearch 0.90.3 and did a fresh 'git clone --branch=kibana-ruby https://github.com/rashidkpc/Kibana.git', and now Kibana is showing blank row data.  Kibana3 seems to have the same behavior.  It does show the data if you click on a each row, however.     

Debian Squeeze / 6.0.6
Ruby 1.8.7
Logstash 1.2.0
Elasticsearch 0.90.3

![image](https://f.cloud.github.com/assets/2956082/1117450/a9b61020-1a4d-11e3-8c77-77987df9575d.png)

**Comment by rashidkpc** [comment]
You'll need to update your default field to be "message" instead of @message

**Comment by alienzrcoming** [comment]
this is an out of the box installation with some logstash inputs & outputs, no filters.  can you offer up a hint of where this is configured?

**Comment by rashidkpc** [comment]
in KibanaConfig.rb

**Comment by alienzrcoming** [comment]
thanks, got it and verified that it woks properly.  much appreciated
