### ISSUE TITLE
Text Panel - HTML mode not work with div style tag.

### ISSUE THREAD

**Issue by anhhuyla** [rashidkpc/kibana2#400]
Hi,

I am using kibana3 and it is really great !
Now I have a problem with text panel (html mode) : 
- It looks like that it not work with div style tag. I put something like this in the text panel : < div style="color:red" > SomeString < / div >

But the "SomeString" is not going to RED, it's still BLACK.

How can I fix this ?

It looks like that it not work with < script > tag too ?

Hope you can help me fix this.

BRs.

**Comment by rashidkpc** [comment]
Wrong repo correct repo is here:
https://github.com/elasticsearch/kibana

Also the text panel's html mode strips unsafe tags via http://docs.angularjs.org/api/ngSanitize.$sanitize
