### ISSUE TITLE
Logstash + Kibana Graphic

### ISSUE THREAD

**Issue by russellseymour** [rashidkpc/kibana2#405]
Good morning,

I apologise for creating an issue about this, but I was not sure how to contact you Rashid.

On the old http://kibana.org website you had an image of how Kibana could be used to see the logs that were being put into Elastic search.  It also had things like Graphite on it as well as showing where Redis or Rabbitmq could be use.

Now that this has been replaced by the Elasticsearch page I cannot find it.  Nor am I am to retrieve it from Google Images.  I have been able to find a simpler one entitled 'How Metrics Work' which was created by you.

Would it be possible to have a copy of the graphic, assuming you know the one I mean?  I need to show people how it all hangs together and yours shows this really well.

Thanks very much, Russell

**Comment by rashidkpc** [comment]
Here you go: https://github.com/rashidkpc/Kibana/blob/gh-pages/images/metrics.png

**Comment by rashidkpc** [comment]
![metrics_on_white](https://f.cloud.github.com/assets/1250387/1262444/f3c65762-2c3e-11e3-8b0b-19855ad5b274.png)

Here's an even more complex one
