### ISSUE TITLE
Kibana 3 broken in Firefox 24

### ISSUE THREAD

**Issue by law** [rashidkpc/kibana2#409]
Loading the Kibana 3 interface (via tarball, not the embedded Kibana 3 that comes with Logstash) in Firefox 24 on multiple OSes (tested with OS X 10.8 and Ubuntu Linux 13.04) results in several errors: 

 Error No index found at <ES_host>:9200/_all/_mapping. Please create at least one index.If you're using a proxy ensure it is configured correctly.

 Error Could not reach <ES_host>:9200/_nodes. If you are using a proxy, ensure it is configured correctly

 Error Could not reach <ES_host>:9200/_aliases. If you are using a proxy, ensure it is configured correctly

This was discovered on a freshly-installed stack of rsyslog 7.4.4, Logstash 1.2.1, Elasticsearch 90.5, and Kibana3-latest (as downloaded from elasticsearch.org as of 10/15/2013)

Loading the same site/configuration on Safari 6.0.5 or Chrome-latest results in Kibana3 returning valid data, as expected.  I am happy to provide browser console logs or whatever else may be needed, just give me a rough idea on how to collect them (I am but a lowly system administrator, after all.  DOM consoles and anything I can't pipe through sed, awk, or grep frighten me :-))

**Comment by rashidkpc** [comment]
I've tested on Firefox 24 on Ubuntu and MacOS, both are working as expect. This sounds like a configuration issue, perhaps related to browser cache of config.js. Clear firefox's cache, restart the browser and test again.

**Comment by bernhardschmidt** [comment]
I can confirm this issue. It could be related to the setup here. Our Kibana is on globally reachable (with Auth) SSL site, so the URL in the browser is https://server/kibana . But elasticsearch is not globally reachable, instead we use "http://localhost:9200" in config.js and port-forward 9200 on the client through SSH.

The following error is logged in the Firefox error console

[18:29:06.293] Blocked loading mixed active content "http://localhost:9200/_aliases" @ https://server/kibana/src/vendor/angular/angular.js:10370

Chrome works fine.

**Comment by bernhardschmidt** [comment]
More details here: https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23/

So as far as I can tell, the problem appears when you use HTTPS in the Kibana URL, but only HTTP to connect to elasticsearch. After disabling the protection on my server Firefox 24 renders Kibana just fine.

**Comment by alpha01** [comment]
This is a proxy config issue and not Kibana. Updating config.js fixed this: 
elasticsearch: "https://"+window.location.hostname+":443"
