### ISSUE TITLE
There are hits, but Kibana doesn't display them.  JS Errors

### ISSUE THREAD

**Issue by arimus** [rashidkpc/kibana2#41]
Can't call method 'concat' of undefined.  Skitch here with a screen shot.  

https://skitch.com/arimus/ebrqk/kibana

Indeed, I can see that the "data" element in the returned json is in one of the loader2.php calls and not in the other, however I'm not familiar at which point Kibana is expecting the request to come back with the data element vs. not.

https://skitch.com/arimus/ebrq7/kibana
https://skitch.com/arimus/ebrxp/kibana

Using Elasticsearch 0.19.3.

**Comment by rashidkpc** [comment]
closing as not reproducible, reopen if this reoccurs
