### ISSUE TITLE
Connection with MongoDB

### ISSUE THREAD

**Issue by vijay2579** [rashidkpc/kibana2#417]
How to connect Kibana with MongoDB.

**Comment by rashidkpc** [comment]
Kibana only supports elasticsearch

**Comment by vijay2579** [comment]
Hi Rashid,

You have implemented using angularjs know so is it possible to make kibana
to get data from mono database instead of elastic search

Regards,
Vijay

**Comment by rashidkpc** [comment]
No, Kibana only supports Elasticsearch. There is no abstraction layer to allow for a different backend.
