### ISSUE TITLE
kibana not displaying dashboard

### ISSUE THREAD

**Issue by PalakGautam** [rashidkpc/kibana2#419]
Hi all ,

I have a amazon linux server  instance and i have installed tomcat on that and i have downloaded kibana on that i have copied it in webapps folder of tomcat,everything worked fine like that on my windows machine ... but here when i access kibana from browser its doesnot display the dash board it just display this
 {{dashboard.current.title}} thats it.Please help .. i have tried  downloading kibana using many wget links from various  websites using github ,elasticsearch but nothing seems to work.
this is the screenshot of what i get while accesing kibana.

![kibana](https://f.cloud.github.com/assets/6523376/2017991/dc0e2dca-8805-11e3-9652-de0f53d63e7d.png)

**Comment by rashidkpc** [comment]
Wrong repo
