### ISSUE TITLE
issue when making a search !

### ISSUE THREAD

**Issue by tdesaules** [rashidkpc/kibana2#42]
Hello !

I have some uri like :

/
/data/blabla/blabal
/data/blabla/balbalbalbal
etc...

When I try to make a search like : Uri:"/"
I always get no "result found..."

Any ideas ?

**Comment by rashidkpc** [comment]
This is an elasticsearch issue. The tokenizer will ignore most/all non-alphanumeric characters. You'd need to either set that field as not_analyzed or create an Analyzer that uses a different Tokenizer. 

This might help:
http://www.elasticsearch.org/guide/reference/index-modules/analysis/

**Comment by tdesaules** [comment]
I'm looking it but I don't know how can I do it.
I create a field named Uri with logstash but not in elasticsearch -_-
