### ISSUE TITLE
Allow configurable default search index

### ISSUE THREAD

**Issue by richadlr** [rashidkpc/kibana2#426]
We have multiple kibana deployments, each connecting to same or different elasticsearch nodes. Thus, the index name is not always the default one ( [logstash-]YYYY.MM.DD ). We are forced to modify the dashboard template json files delivered with kibana (essentially logstash.json), plus a few customs to reflect the correct index ( index.pattern ). And have to repeat this everytime a new kibana release brings enhanced templates.

We would need a mechanism to specify the default search index that kibana would override before realizing the template and querying elasticsearch.

Setting could be in **config.js**, similar format as kibana_index ( kibana_index: "kibana-int", )
default_search_index: "logstash-env1-",

**Logic** would be:

if index_defined_in_dashboard != "logstash-"
  index = index_defined_in_dashboard
else
  index = default_search_index

**Comment by rashidkpc** [comment]
It appears you've filed this in the wrong repository? See here: https://github.com/elasticsearch/kibana

**Comment by richadlr** [comment]
Thanks, created https://github.com/elasticsearch/kibana/issues/1009 instead.
