### ISSUE TITLE
Display JSON structured @fields

### ISSUE THREAD

**Issue by jkoppe** [rashidkpc/kibana2#44]
Logstash will happily pass along JSON structured @fields via many outputs (I've checked file, amqp, elasticsearch, but I imagine most outputs will work this way).  I produce a few JSON @fields and would like to be able to see this in the web interface.  Loggly does something similar and included this in their blog post a few months ago: http://loggly.com/blog/2011/06/on-the-way-to-impressive/ (specific screenshot URL: http://loggly.com/assets/4e24a17edabe9d56ea003ecb/status_code_json.png).

Here's a simple query on my elasticsearch showing a tiny bit of my JSON @field, "mdc":

<pre>
--> curl -s http://localhost:9311/logstash-2012.07.06/_search?q=webapp | /tmp/pretty_print_json
{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "hits": {
        "hits": [
            {
                "_id": "kYYc_eOrSHicqVogfP29Dg",
                "_index": "logstash-2012.07.06",
                "_score": 0.018579213000000001,
                "_source": {
                    "@fields": {
                        "instance": "us-qa-tomcat",
                        "level": "ERROR",
                        "logger": "servlet.jsp",
                        "mdc": {
                            "jsonRequestSnapshot": {
                                "cookies": {
                                    "JSESSIONID": "0106FA007566B27BD0395D57A1941533.us-qa_localhost",

</pre>

**Comment by jkoppe** [comment]
pull req in https://github.com/rashidkpc/Kibana/pull/48

**Comment by kwilczynski** [comment]
+1 to this!

It would be amazing to see an ability to make anything in @fields immediately available as table, and as active elements on which you would be able to perform some basic analysis.

**Comment by rashidkpc** [comment]
Had to remove the code for the pull as it broke the this/not-this button functionality. Consider adding into the kibana-ruby branch?

**Comment by jkoppe** [comment]
yep, will take a look!

**Comment by rashidkpc** [comment]
Implemented in kibana-ruby e95dbe3f47

Maybe, can someone test this for me? It seems to work for me, but I'm testing with a string containing json, so I'm not totally sure.

**Comment by jkoppe** [comment]
i tested this and still see Object[].  will find you on irc
