### ISSUE TITLE
no search results, endless wait, no errors

### ISSUE THREAD

**Issue by msacks** [rashidkpc/kibana2#49]
I have hooked up Kibana according to the documentation successfully. I can run searches just fine on my logstash UI.
I fire up Kibana, try to execute the search and the "searching" animated graphic just spins forever. 

I have output php errors turned on, and nothing.

Using CentOS 5 / Apache2 / PHP53

**Comment by rashidkpc** [comment]
php5-curl installed? Maybe open up a javascript console and see if there's any error there?

**Comment by msacks** [comment]
php built with --with-curl=shared
curl-7.15.5-15.el5

Hangs on:
Kibana/loader2.php?page=eyJzZWFyY2giOiIiLCJmaWVsZHMiOlsiIl0sIm9mZnNldCI6MCwidGltZWZyYW1lIjoiYWxsIiwiZ3JhcGhtb2RlIjoiY291bnQiLCJzdGFtcCI6MTM0Mzc5NTM1NzAyNn0=&_=1343851483568

Request Headers
    13:04:44.384

  Accept:_/_Accept-Encoding:gzip, deflateAccept-Language:en-us,en;q=0.5Connection:keep-aliveHost:somebox.comReferer:http://somebox.com/Kibana/index.phpUser-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:12.0) Gecko/20100101 Firefox/12.0X-Requested-With:XMLHttpRequest

```
Sent Cookie
__gads:ID
```

**Comment by rashidkpc** [comment]
I wonder if its having trouble contacting your elasticsearch server? You might try finding me (or someone) in #logstash on freenode for some realtime debugging.

**Comment by msacks** [comment]
Hey, thanks, that sounds good. When are your office hours?
