### ISSUE TITLE
Changing Default Fields Shown

### ISSUE THREAD

**Issue by tintii** [rashidkpc/kibana2#54]
Hi,

I'm currently using kibana to show my logs however I'm finding some trouble to increase the fields shown by default. Currently it shows time and message.

Is there a way to have more fields displayed by default?

thanks

**Comment by rashidkpc** [comment]
Added in kibana-ruby  99d1856

**Comment by thisguycodes** [comment]
It'd be a lot more useful if this was dynamic. Like being able to set the fields shown per search. We like to have some of the useful streams up on monitors in the office and different types of logs use different field names.
