### ISSUE TITLE
What would be needed to use Kibana as a general Elasticsearch interface?

### ISSUE THREAD

**Issue by PanMan** [rashidkpc/kibana2#57]
As in the title: What would be needed to use Kibana on an Elasticsearch cluster that doesn't index logs? A lot of the features and graphs would be nice to have on other searches as well. I'm willing to dive into this, but I have no idea (yet) how logstash specific it is. Thnx!

**Comment by rashidkpc** [comment]
In the current version it would likely be quite an endeavor. A newer ruby based version should be out within a week with better query building and request making classes.
