### ISSUE TITLE
All git urls point to PHP project

### ISSUE THREAD

**Issue by thoughtpunch** [rashidkpc/kibana2#59]
You might want to put the Ruby project in it's own Github project i.e. "https://github.com/rashidkpc/kibana-ruby"

Right now it's impossible to clone the ruby fork, as it points to the PHP project.

**Comment by rashidkpc** [comment]
Try this: git clone --branch=kibana-ruby git@github.com:rashidkpc/Kibana.git

I'll add the above to the README.md

**Comment by thoughtpunch** [comment]
Thanks!
