### ISSUE TITLE
Forced query/filter term in config

### ISSUE THREAD

**Issue by untergeek** [rashidkpc/kibana2#6]
I send multiple customer environment logs to the same ES backend.  I would like to have separate kibana installs which only see the specified customer data forced by tag, e.g. @tags:"Customer1"

I suppose this could be accomplished by a filter as well as appending a query, but that's what I would request: A way to force kibana to only show data containing a given tag, or other query term match.

**Comment by rashidkpc** [comment]
[master fd520dc] issue #6 - forced query. Added filter_string to config
 2 files changed, 11 insertions(+), 1 deletions(-)
