### ISSUE TITLE
Feature: Add+Rescore button in score/trend views

### ISSUE THREAD

**Issue by tabletcorry** [rashidkpc/kibana2#60]
Perhaps add a button in the score views that allow you to create a new score with that item as the search query.

This would be equivalent to the search button (in that it adds to the query) but would take you back to the score view rather than the results view.

This would allow you to chase down the culprit tag (or any other array-type field) quickly.

**Comment by rashidkpc** [comment]
Added in kibana-ruby 9ff3fe0
