### ISSUE TITLE
Handle php warnings

### ISSUE THREAD

**Issue by falkenbt** [rashidkpc/kibana2#65]
Hi, 
due to php warnings returned by loader2.php kibana did not show any results. Setting "displayErrors Off" in the php.ini resolved this issue. 

These are the warnings I'm getting:
Warning: Creating default object from empty value in xxx/kibana/htdocs/loader2.php on line 163

Warning: Creating default object from empty value in xxx/kibana/htdocs/loader2.php on line 175

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in xxx/kibana/htdocs/loader2.php on line 184

What would be the best way to handle this? Just disabling warnings doesn't seem right to me. 

Thanks
Thomas

**Comment by rashidkpc** [comment]
Yeah, this started with PHP 5.4 which turned on E_STRICT by default. I merged a pull to master that perhaps fixed the object creation warnings. Not sure if you're running a tagged version or master. You'll need to set the timezone in php.ini or in config.php near the bottom to avoid the timezone warning. 

Early next week I'll be replacing master, currently PHP, with the shiny new Ruby version from this branch: https://github.com/rashidkpc/Kibana/tree/kibana-ruby

**Comment by falkenbt** [comment]
Ok I will check that out, thanks. I am running master. 
Regarding Ruby, which server would you recommend? Or do you include one (it seems so from the installation instructions). I'm not sure yet how the installation would work in our case (no internet access, no ruby (no gem) installed...

**Comment by rashidkpc** [comment]
I run it under passenger with Apache, but it uses the Sinatra framework and can run its own little standalone web server. 

I'll look into packing up the whole shebang with jRuby, much like logstash.

**Comment by falkenbt** [comment]
Wrapping it with jRuby would be great, this would really help us and probably many other who don't have ruby installed. This way it would be easy to get started without root, just like with logstash.

**Comment by rashidkpc** [comment]
Gonna close this since the PHP version is deprecated. I do want to wrap up Kibana in jRuby though.
