### ISSUE TITLE
There doesn't seem to be a way to separate the access log from stderr

### ISSUE THREAD

**Issue by timbunce** [rashidkpc/kibana2#69]
The access log goes to stderr by default. Some way to send it to stdout (or disable it) would be appreciated, so it's kept separate from error messages.

**Comment by rashidkpc** [comment]
Couple options. If you want to redirect to stdout:
ruby kibana.rb 2>&1

Or to a file:
ruby kibana.rb 2> stderr.log

Alternatively, you can run kibana with rackup and a config.ru file via 'rackup config.ru'

Example config.ru w/ logging:

require 'kibana'
require 'rubygems'
require 'sinatra'

set :environment, ENV['RACK_ENV'].to_sym
set :app_file,     'kibana.rb'
disable :run

root_dir = File.dirname(**FILE**)
set :root,root_dir
stdout = File.new('sinatra-stdout.log','a')
stderr = File.new('sinatra-stderr.log','a')
$stdout.reopen(stdout)
$stderr.reopen(stderr)

run Sinatra::Application

**Comment by timbunce** [comment]
Thanks, but none of those address the underlying issue that the access log is being sent to stderr which is _also_ used for errors. So the errors and the log are mixed together.

A simple fix would be to change the code so the web server access log is sent to stdout. I'd offer a patch but I'm not familiar with ruby/sinatra. [...later...] So I dug around and turned up https://github.com/sinatra/sinatra/issues/484 It seems lots of people are struggling with this. It does seem very odd to send access logs to stderr. Oh well.
