### ISSUE TITLE
Timezone setting

### ISSUE THREAD

**Issue by rashidkpc** [rashidkpc/kibana2#7]
Allow for user configurable timezones. This will probably require some kind of cookie to coordinate the PHP and Javascript. Open to other suggestions though.

**Comment by rashidkpc** [comment]
Or pass timezone in the json response

**Comment by phobos182** [comment]
I am experiencing some issues with this. Basically all of our Servers are set for UTC. The logs show up correctly in Logstash with the correct time. The "Last 15minute" feature does not work. I'm thinking it's because my timezone is US/Pacific. And it's calculating UTC incorrectly?

**Comment by robinbowes** [comment]
I'm not sure if I'm also getting bitten by this.

All my servers are in UTC. I'm in the UK, so UTC+1.

It seems that if the search goes back before midnight, then it is truncated at midnight.

So, right now, it's 13:05. Last 5m, last 60m, last 4h, last 12h all work OK. But anything before that results in the search being truncated at midnight UTC, ie. 2012-04-17T01:00:00.

Similarly, if I try and search in a time period over the midnight boundary, then the search is truncated at midnight.

eg. try and search 2012-04-15T22:00:00 to 2012-04-16T02:00:00 and the time period gets changed to 2012-04-16T01:00:00 to 2012-04-16T02:00:00

I'll try and ping you in #logstash later on today.

**Comment by rashidkpc** [comment]
If you set date.timezone = UTC in php.ini does it work right? There might be a flaw in the way I select which indices to query.

**Comment by robinbowes** [comment]
Sorry for the late reply (I just noticed the msg!).

It seems that this was a chrome bug, ie. it worked OK in Safari + Firefox.

R.

**Comment by rashidkpc** [comment]
Added in kibana-ruby  59289da

Timezone can be set to 'user' to allow the user's browser to decide, or it can be set to a timezone string.
