### ISSUE TITLE
Add support for nested fields

### ISSUE THREAD

**Issue by rurounijones** [rashidkpc/kibana2#70]
First off, Kibana is spectacular! Right, onto the request.

I am currently messing around with creating log files with nested JSON structures. Logstash itself and ElasticSearch do not seem to have any trouble with them but both Kibana and the Logstash WebUI have trouble with them.

A sample of the JSON I am trying to display is here: https://gist.github.com/3694987

As you can see the field contains an array of hashes, each with various fields.

As a first step it would be lovely to see Kibana be able to display these hashes in a subtable of the field with names / values (at the moment it displays only "[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" ).

Ideally in future it would be nice to be able to add / exclude records based on these fields like you can on the top-level fields (assuming that is even possible)

(I have not tried displaying an array of strings rather than hashes so I am not sure how Kibana handles them)

**Comment by rurounijones** [comment]
Gah, none of these commits triggered a notification so I wasn't aware that they were done. Thank you very much for working on this.

**Comment by rashidkpc** [comment]
Oh yeah, fair to say this is done. switched to dot notation
