### ISSUE TITLE
kibana-ruby extremely slow

### ISSUE THREAD

**Issue by kakbit** [rashidkpc/kibana2#71]
First; Thank you!
I really like Kibana.
The php-version of Kibana loads in about 0.3 s
The ruby-version in 30 s and produces outputs like this :
http://pastebin.com/KrytfNBv
The browser says:
Oops! Something went terribly wrong.
I'm on a Ubuntu 12.04 x86_64 with ruby 1.8.7
I followed your install instruction but it looks like something is missing.

**Comment by rashidkpc** [comment]
It appears that it can not contact your Elasticsearch server. Make sure Elasticsearch is set in KibanaConfig.rb. If you continue to experience issues come see us in #logstash on irc.freenode.net

**Comment by chriscareycode** [comment]
The answer you need is to disable the avahi-daemon service and it will fix it.
