### ISSUE TITLE
Score doesn't show all

### ISSUE THREAD

**Issue by kakbit** [rashidkpc/kibana2#77]
I've noticed from time to time that the score feature doesn't show what I think it should.
I'm usually using @source_host -> score to sort out the host I want to focus on but I've noticed that some hosts are missing from time to time.
If I do a search on the same host or file I will find it but score won't.
If I after I found the logs do a @source_host -> score it will show.

**Comment by r-duran** [comment]
It is because "Analyze_limit" is set to 2000 by default in KibanaConfig.rb. So if there is no log for some source_hosts in latest 2000 logs you will not see it in score table. You can increase that limit.

**Comment by kakbit** [comment]
Yes, that helped.
Thank you!
