### ISSUE TITLE
ISO8601

### ISSUE THREAD

**Issue by kakbit** [rashidkpc/kibana2#78]
How do I change the (faulty) date format to ISO8601 format or whatever format I like on the ruby version?
Shouldn't that be an option?

We Swedish nerds honour  the use of ISO 8601 because it's the standard within the language :-)

**Comment by drewp** [comment]
Which date presentations did you want to change? The result of /api/search seems to be fine. Then there's a chopped one on each log line (but the time components are still in a good order), and a similar thing on the graph.

**Comment by rashidkpc** [comment]
I've added a Time_formation option to KibanaConfig.rb with b613b12

Syntax is here, though I also included an example for iso8601 in the config file.
http://blog.stevenlevithan.com/archives/date-time-format

**Comment by kakbit** [comment]
Perfect,
Thank you!
/Patric

Rashid Khan wrote:
