### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by rashidkpc** [rashidkpc/kibana2#9]
Define supported browsers. We know Firefox 3.6 doesn't work. Either support older browsers or display a message about browser support.

**Comment by robert-martens** [comment]
- Chrome "18.0.1025.39 beta-m" will load the main page and then the tab will freeze up.  Chrome's CPU usage jumps significantly.  Not sure why this happens.
- MSIE 8 needed to have the console logging removed from js files (similar to issue #15) and flot's `excanvas.min.js` added to index.php:
  
  ```
  <!--[if IE]><script language="javascript" type="text/javascript" 
  src="js/excanvas.min.js"></script><![endif]-->
  ```

**Comment by robert-martens** [comment]
- Chrome "17.0.963.56 m" seems to work fine.

**Comment by azulcactus** [comment]
To help with research, after issue #15's fix Firefox 3.6 works fine for me.

MSIE 8 doesn't work for me, I get:
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322; MS-RTC LM 8)
Message: Expected identifier, string or number
Line: 705
Char: 13
Code: 0
URI: http://10.38.189.56/kibana/js/ajax.js

It seems to not like the trailing commas without anything after them in the creation of the graph series JSON.  If I remove them (there are about 8 or so, note my line numbers in ajax.js include change I have pending for push 18) I then get:
Webpage error details

Message: 'JSON' is undefined
Line: 97
Char: 9
Code: 0
URI: http://10.38.189.56/kibana/js/ajax.js

Some good info on that error here: http://stackoverflow.com/questions/5339232/json-is-undefined-error-in-javascript-in-internet-explorer
One of the comments there also notes the trailing comma issue.

I added json2.js (https://github.com/douglascrockford/JSON-js) to index.php and now I do get data back in Kibana in IE 8 and a new error when it attempts to draw the chart:

Message: 'window.G_vmlCanvasManager' is null or not an object
Line: 6
Char: 11617
Code: 0
URI: http://10.38.189.56/kibana/js/jquery.flot.min.js

This is solved by adding excanvas.min.js as robert mentions.  After that, I have a working Kibana in IE 8!  The style sheet renders a bit strange but it is very usable.  I'd be happy to issue a pull request for my above changes.

**Comment by rashidkpc** [comment]
The pull request would be much appreciated.

**Comment by petebowden** [comment]
MSIE 8 - Error when clicking on search: Object doesn't support this action  ajax.js, line 67 character 5

Looks like it has to do with the "delete" function and IE. Delete does not work with explicit assignment (this.x or window.x) in IE.

See: http://perfectionkills.com/understanding-delete/

I'm trying to test whether just changing the value to null will work.

**Comment by tpischke** [comment]
IE8 not working with latest Kibana, installed today.  Page renders somewhat but no graph or results shown:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.2; .NET4.0C; .NET4.0E)
Timestamp: Mon, 24 Sep 2012 14:26:50 UTC

Message: Object doesn't support this property or method
Line: 124
Char: 13
Code: 0
URI: http://setzehorn.bedag.ch:5601/lib/js/ajax.js

Message: Object doesn't support this action
Line: 39
Char: 5
Code: 0
URI: http://setzehorn.bedag.ch:5601/lib/js/ajax.js

PS:  Tried to attach a screenshot, but it seems github doesn't support atttachments?

**Comment by rashidkpc** [comment]
Added try/catch for delete to fix the 'object doesn't support this action' issue. There's still some code in the recently added dateFormat function that ie8 doesn't like. Will investigate more.

**Comment by tpischke** [comment]
Great!  I don't suppose there's a nightly build or something I can try out?

**Comment by rashidkpc** [comment]
You can pull master, however IE8 is still broken due to the dateFormat function.

**Comment by tpischke** [comment]
Grabbed the latest code just to see if it worked a little better, but behavior is the same.  Here's the latest error info:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.2; .NET4.0C; .NET4.0E)
Timestamp: Wed, 26 Sep 2012 15:52:33 UTC

Message: Exception thrown and not caught
Line: 81
Char: 20
Code: 0
URI: http://setzehorn.bedag.ch:5601/lib/js/lib/date.js

Message: Exception thrown and not caught
Line: 81
Char: 20
Code: 0
URI: http://setzehorn.bedag.ch:5601/lib/js/lib/date.js

**Comment by rashidkpc** [comment]
Dance party: IE8 tested and seems to work. Safari too. I'm going to close this for now. If anyone finds issues with other browsers, open a new issue. 

Cheers
Rashid

**Comment by tpischke** [comment]
Awesome, IE8 working great for me, Thanks!
