### ISSUE TITLE
Add hitcount graph to stream page or live button on main page

### ISSUE THREAD

**Issue by stonith** [rashidkpc/kibana2#92]
Option #1: add the hitcount graph to the stream page

Option #2: add a "live" feature to the main page that updates in realtime with the selected filter and displayed fields

Personally I'd prefer #2, it looks nicer :D

**Comment by rashidkpc** [comment]
Added an events/sec rate graph to the stream page. Still want to make a live button though. Watch for the graph to fill in from the right in the bar at the top.
