### ISSUE TITLE
No Gemfile.lock

### ISSUE THREAD

**Issue by kmullin** [rashidkpc/kibana2#94]
When other people clone your repo, and install the Gems listed inside the Gemfile, they might be getting different gem versions than what you are developing with. This can cause all sorts of problems.

As the main developer of this project, you should add your Gemfile.lock to the repository guaranteeing that others use the same exact gem versions that you are developing with.

**Comment by jbussdieker** [comment]
This also would help with `bundle install --deployment` for creating standalone builds.
